[tool.poetry]
name = "hexlet-code"
version = "y"
description = "y"
authors = ["y"]
license = "y"
readme = "README.md"
packages = [{include = "brain_games"}]

[tool.poetry.dependencies]
python = "y"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
